# Generated by Django 5.2.10 on 2026-01-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Navigator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("img", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
