# Generated by Django 5.2.10 on 2026-01-28 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
