# Generated by Django 5.2.10 on 2026-02-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_created_at_user_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigator",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="navigators",
                to="users.user",
            ),
        ),
    ]
