# Generated by Django 5.2.10 on 2026-02-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_navigator_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigator",
            name="url",
            field=models.CharField(max_length=1024),
        ),
    ]
