# Generated by Django 5.2.10 on 2026-03-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_navigator_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='img',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
