# Generated by Django 5.2.10 on 2026-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_navigator_img_alter_navigator_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='url',
            field=models.CharField(max_length=1024),
        ),
    ]
