# Generated by Django 5.2.10 on 2026-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_navigator_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='img',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='navigator',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]

