# Generated by Django 5.2.10 on 2026-08-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_navigator_img_navigator_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLauncher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=1024)),
                ('img', models.CharField(blank=True, default='', max_length=1024)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_launchers', to='users.user')),
            ],
        ),
    ]
