# Generated by Django 5.2.10 on 2026-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("album_id", models.CharField(max_length=100)),
                ("album_title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("cover", models.ImageField(default="", upload_to="music/covers/")),
                ("audio", models.FileField(upload_to="music/audio/")),
                ("url", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
