# Generated by Django 5.2.10 on 2026-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="audio",
            field=models.FileField(upload_to="media/music/audio/"),
        ),
        migrations.AlterField(
            model_name="music",
            name="cover",
            field=models.ImageField(default="", upload_to="media/music/covers/"),
        ),
        migrations.AlterField(
            model_name="music",
            name="url",
            field=models.TextField(blank=True),
        ),
    ]
