# Generated by Django 5.2.10 on 2026-02-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_alter_music_audio_alter_music_cover_alter_music_url"),
        ("users", "0004_navigator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="users.user",
            ),
        ),
    ]
