# Generated by Django 5.2.10 on 2026-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='album_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='media/music/covers/'),
        ),
    ]

