# Generated by Django 5.2.10 on 2026-02-06 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0002_todolistmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ToDoListModel",
        ),
    ]
