# Generated by Django 5.2.10 on 2026-02-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0003_delete_todolistmodel"),
        ("users", "0004_navigator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="users.user",
            ),
        ),
    ]
