# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0004_document_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
