# Generated by Django 5.2.10 on 2026-02-06 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToDoListModel",
            new_name="ToDoList",
        ),
    ]
