# Generated by Django 5.2.10 on 2026-02-06 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0002_rename_todolistmodel_todolist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="complated",
            new_name="completed",
        ),
    ]
