# Generated by Django 5.2.10 on 2026-02-06 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0003_rename_complated_todolist_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="todolist",
            old_name="updated_at",
            new_name="updated_time",
        ),
    ]
