# Generated by Django 5.2.10 on 2026-08-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_app_launcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coin', '抛硬币'), ('dice', '掷骰子'), ('yesno', 'Yes/No'), ('random', '随机数'), ('pick', '多选一')], max_length=16)),
                ('result', models.CharField(max_length=255)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_histories', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
