# Generated by Django 5.2.10 on 2026-06-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_navigator_img_navigator_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('contact', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=20)),
                ('reply', models.TextField(blank=True, default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='users.user')),
            ],
        ),
    ]

