# Generated by Django 6.0.1 on 2026-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('site_title', models.CharField(default='Raspberrypi Console', max_length=120)),
                ('login_title', models.CharField(default='欢迎回来', max_length=120)),
                ('login_slogan', models.CharField(default='快速进入你的个人聚合空间', max_length=255)),
                ('theme', models.CharField(default='cyber', max_length=50)),
                ('show_petals', models.BooleanField(default=True)),
                ('top_level_order', models.JSONField(default=list)),
                ('submenu_orders', models.JSONField(default=dict)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
