# Generated by Django 6.0.1 on 2026-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_websitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='corner_style',
            field=models.CharField(default='soft', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='density',
            field=models.CharField(default='balanced', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='font_scale',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='surface_style',
            field=models.CharField(default='glass', max_length=50),
        ),
    ]
