# Generated by Django 5.2.10 on 2026-02-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0005_alter_navigator_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="QimenCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_str", models.CharField(blank=True, max_length=32)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("solar", models.BooleanField(default=True)),
                ("parsed_datetime", models.DateTimeField(blank=True, null=True)),
                ("seed", models.BigIntegerField(default=0)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qimen_calculations",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QimenPalace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("gate", models.CharField(max_length=8)),
                ("star", models.CharField(max_length=16)),
                ("god", models.CharField(max_length=16)),
                ("tip", models.CharField(blank=True, max_length=255)),
                (
                    "calc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palaces",
                        to="qi_men_dun_jia.qimencalculation",
                    ),
                ),
            ],
        ),
    ]
