# Generated by Django 5.2.10 on 2026-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qi_men_dun_jia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_model",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_provider",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
