# Generated by Django 5.2.10 on 2026-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qi_men_dun_jia", "0002_qimencalculation_analysis_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_status",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
