# Generated by Django 5.2.10 on 2026-02-21 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qi_men_dun_jia", "0003_qimencalculation_analysis_error_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qimencalculation",
            name="analysis_error",
        ),
        migrations.RemoveField(
            model_name="qimencalculation",
            name="analysis_status",
        ),
    ]
