# Generated by Django 5.2.10 on 2026-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qi_men_dun_jia", "0004_remove_qimencalculation_analysis_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_status",
            field=models.CharField(default="none", max_length=16),
        ),
    ]
