# Generated by Django 5.2.10 on 2026-02-21 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qi_men_dun_jia", "0005_qimencalculation_analysis_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qimencalculation",
            name="analysis_status",
        ),
    ]
