# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qi_men_dun_jia", "0006_remove_qimencalculation_analysis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="qimencalculation",
            name="analysis_status",
            field=models.CharField(default="none", max_length=16),
        ),
    ]
